# Generated by Django 3.1.1 on 2020-09-23 02:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker_app', '0006_auto_20200917_2142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskcategory',
            name='date',
        ),
        migrations.AddField(
            model_name='memberentry',
            name='date',
            field=models.DateField(default=datetime.datetime.today),
        ),
    ]
