# Generated by Django 3.1.1 on 2020-10-12 07:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker_app', '0008_auto_20200923_1229'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubmittedPeriod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startDate', models.DateField(default=datetime.datetime.today)),
                ('endDate', models.DateField(default=datetime.datetime.today)),
            ],
        ),
    ]
