# Generated by Django 3.1.1 on 2020-10-26 04:51

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker_app', '0011_auto_20201020_0159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='created',
            field=models.DateField(default=datetime.datetime.today),
        ),
        migrations.AlterField(
            model_name='group',
            name='expiry',
            field=models.DateField(default=datetime.datetime(2021, 2, 15, 15, 51, 41, 337410)),
        ),
        migrations.CreateModel(
            name='MemberRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('is_owner', models.BooleanField()),
                ('is_leader', models.BooleanField()),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tracker_app.group')),
            ],
        ),
    ]
