# Generated by Django 3.1.1 on 2020-10-26 06:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker_app', '0012_auto_20201026_1551'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupmember',
            name='roles',
        ),
        migrations.AddField(
            model_name='groupmember',
            name='ro9les',
            field=models.ManyToManyField(to='tracker_app.MemberRole'),
        ),
        migrations.AlterField(
            model_name='group',
            name='expiry',
            field=models.DateField(default=datetime.datetime(2021, 2, 15, 17, 29, 16, 149294)),
        ),
    ]
