# Generated by Django 3.1.1 on 2020-10-26 06:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker_app', '0013_auto_20201026_1729'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groupmember',
            old_name='ro9les',
            new_name='roles',
        ),
        migrations.AlterField(
            model_name='group',
            name='expiry',
            field=models.DateField(default=datetime.datetime(2021, 2, 15, 17, 29, 42, 257742)),
        ),
    ]
