# Generated by Django 3.1.1 on 2020-10-29 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker_app', '0014_auto_20201026_1729'),
        ('tracker_app', '0012_auto_20201028_0618'),
    ]

    operations = [
    ]
