# Generated by Django 3.1.1 on 2020-10-29 07:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker_app', '0015_merge_20201029_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='expiry',
            field=models.DateField(default=datetime.datetime(2021, 2, 18, 18, 32, 28, 884377)),
        ),
    ]
